In [3]:
import pandas as pd

In [4]:
world = pd.DataFrame({
    "name": ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola"],
    "continent": ["Asia", "Europe", "Africa", "Europe", "Africa"],
    "area": [652230, 28748, 2381741, 468, 1246700],
    "population": [25500100, 2831741, 37100000, 78115, 20609294],
    "gdp": [20343000000, 12960000000, 188681000000, 3712000000, 100990000000]
})

In [5]:
world

          name continent     area  population           gdp
0  Afghanistan      Asia   652230    25500100   20343000000
1      Albania    Europe    28748     2831741   12960000000
2      Algeria    Africa  2381741    37100000  188681000000
3      Andorra    Europe      468       78115    3712000000
4       Angola    Africa  1246700    20609294  100990000000

---

In [8]:
def big_countries(world):
    big_countries_df = world[(world['area'] >= 3000000) | (world['population'] >= 25000000)]
    return big_countries_df[['name', 'population', 'area']]

In [9]:
big_countries(world)

          name  population     area
0  Afghanistan    25500100   652230
2      Algeria    37100000  2381741