In [1]:
import pandas as pd

In [3]:
products = pd.DataFrame({
    "product_id": [0, 1, 2, 3, 4],
    "low_fats": ["Y", "Y", "N", "Y", "N"],
    "recyclable": ["N", "Y", "Y", "Y", "N"]
})

In [4]:
products

   product_id low_fats recyclable
0           0        Y          N
1           1        Y          Y
2           2        N          Y
3           3        Y          Y
4           4        N          N

---

In [7]:
def find_products(products):
    find_products_df = products[(products['low_fats'] == 'Y') & (products['recyclable'] == 'Y')]
    return find_products_df[['product_id']]

In [8]:
find_products(products)

   product_id
1           1
3           3