In [1]:
import pandas as pd

In [2]:
customers = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "name": ["Joe", "Henry", "Sam", "Max"]
})

In [3]:
orders = pd.DataFrame({
    "id": [1, 2],
    "customerId": [3, 1]
})

In [4]:
customers

   id   name
0   1    Joe
1   2  Henry
2   3    Sam
3   4    Max

In [5]:
orders

   id  customerId
0   1           3
1   2           1

---

In [10]:
def find_customers(customers, orders):
    find_customers_df = customers[~customers['id'].isin(orders['customerId'])]
    return find_customers_df[['name']].rename(columns={'name':'Customers'})

In [11]:
find_customers(customers, orders)

  Customers
1     Henry
3       Max