In [1]:
import pandas as pd

In [2]:
views = pd.DataFrame({
    "article_id": [1, 1, 2, 2, 4, 3, 3],
    "author_id": [3, 3, 7, 7, 7, 4, 4],
    "viewer_id": [5, 6, 7, 6, 1, 4, 4],
    "view_date": ["2019-08-01", "2019-08-02", "2019-08-01", "2019-08-02", "2019-07-22", "2019-07-21", "2019-07-21"]
})

In [3]:
views

   article_id  author_id  viewer_id   view_date
0           1          3          5  2019-08-01
1           1          3          6  2019-08-02
2           2          7          7  2019-08-01
3           2          7          6  2019-08-02
4           4          7          1  2019-07-22
5           3          4          4  2019-07-21
6           3          4          4  2019-07-21

---

In [5]:
def article_views(views):
    article_views_df = views[(views['author_id'] == views['viewer_id'])]
    article_views_df = article_views_df[['author_id']].drop_duplicates()
    article_views_df = article_views_df.sort_values(by='author_id')
    return article_views_df.rename(columns={'author_id':'id'})

In [6]:
article_views(views)

   id
5   4
2   7