In [1]:
import pandas as pd

In [2]:
tweets = pd.DataFrame({
    "tweet_id": [1, 2],
    "content": ["Let us Code", "More than fifteen chars are here!"]
})

In [3]:
tweets

   tweet_id                            content
0         1                        Let us Code
1         2  More than fifteen chars are here!

---

In [4]:
def invalid_tweets(tweets):
    invalid_tweets_df = tweets[tweets['content'].str.len() > 15]
    return invalid_tweets_df[['content']]

In [5]:
invalid_tweets(tweets)

                             content
1  More than fifteen chars are here!