In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "employee_id": [2, 3, 7, 8, 9],
    "name": ["Meir", "Michael", "Addilyn", "Juan", "Kannon"],
    "salary": [3000, 3800, 7400, 6100, 7700]
})

In [3]:
employees

   employee_id     name  salary
0            2     Meir    3000
1            3  Michael    3800
2            7  Addilyn    7400
3            8     Juan    6100
4            9   Kannon    7700

---

In [9]:
def calculate_special_bonus(employees):
    employees['bonus'] = employees[(employees['employee_id'] % 2 == 1) & (~employees['name'].str.startswith('M'))]['salary']
    employees['bonus'] = employees['bonus'].fillna(0)
    return employees[['employee_id', 'bonus']].sort_values(by='employee_id')

calculate_special_bonus(employees)

   employee_id   bonus
0            2     0.0
1            3     0.0
2            7  7400.0
3            8     0.0
4            9  7700.0