In [1]:
import pandas as pd

In [2]:
users = pd.DataFrame({
    "user_id": [1, 2],
    "name": ["aLice", "bOB"]
})

In [3]:
users

   user_id   name
0        1  aLice
1        2    bOB

---

In [4]:
def fix_names(users):
    users["name"] = users["name"].str.capitalize()
    return users.sort_values(by="user_id")

In [5]:
fix_names(users)

   user_id   name
0        1  Alice
1        2    Bob