In [1]:
import pandas as pd

In [2]:
patients = pd.DataFrame({
    "patient_id": [1, 2, 3, 4, 5],
    "patient_name": ["Daniel", "Alice", "Bob", "George", "Alain"],
    "conditions": ["YFEV COUGH", "", "DIAB100 MYOP", "ACNE DIAB100", "DIAB201"]
})

In [3]:
patients

   patient_id patient_name    conditions
0           1       Daniel    YFEV COUGH
1           2        Alice
2           3          Bob  DIAB100 MYOP
3           4       George  ACNE DIAB100
4           5        Alain       DIAB201

---

In [5]:
def find_patients(patients):
    find_patients_df = patients[patients['conditions'].str.contains(r'\bDIAB1')]
    return find_patients_df

In [6]:
find_patients(patients)

   patient_id patient_name    conditions
2           3          Bob  DIAB100 MYOP
3           4       George  ACNE DIAB100