In [1]:
import pandas as pd

In [2]:
students = pd.DataFrame({
    "student_id": [101, 53, 128, 3],
    "name": ["Ulysses", "William", "Henry", "Henry"],
    "age": [13, 10, 6, 11]
})

In [3]:
students

   student_id     name  age
0         101  Ulysses   13
1          53  William   10
2         128    Henry    6
3           3    Henry   11

---

In [4]:
def selectData(students: pd.DataFrame) -> pd.DataFrame:
    return students.loc[students['student_id'] == 101, ['name', 'age']]

In [5]:
selectData(students)

      name  age
0  Ulysses   13