In [1]:
import pandas as pd

In [2]:
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4, 5, 6],
    "name": ["Ella", "David", "Zachary", "Alice", "Finn", "Violet"],
    "email": [
        "emily@example.com",
        "michael@example.com",
        "sarah@example.com",
        "john@example.com",
        "john@example.com",
        "alice@example.com"
    ]
})

In [3]:
customers

   customer_id     name                email
0            1     Ella    emily@example.com
1            2    David  michael@example.com
2            3  Zachary    sarah@example.com
3            4    Alice     john@example.com
4            5     Finn     john@example.com
5            6   Violet    alice@example.com

---

In [4]:
def dropDuplicateEmails(customers):
    customers.drop_duplicates(subset='email', keep='first', inplace=True)
    return customers

In [5]:
dropDuplicateEmails(customers)

   customer_id     name                email
0            1     Ella    emily@example.com
1            2    David  michael@example.com
2            3  Zachary    sarah@example.com
3            4    Alice     john@example.com
5            6   Violet    alice@example.com