In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "name": ["Jack", "Piper", "Mia", "Ulysses"],
    "salary": [19666, 74754, 62509, 54866]
})

In [3]:
employees

      name  salary
0     Jack   19666
1    Piper   74754
2      Mia   62509
3  Ulysses   54866

---

In [4]:
def modifySalaryColumn(employees):
    employees['salary'] = employees['salary'] * 2
    return employees

In [5]:
modifySalaryColumn(employees)

      name  salary
0     Jack   39332
1    Piper  149508
2      Mia  125018
3  Ulysses  109732