In [1]:
import pandas as pd

In [2]:
students = pd.DataFrame({
    "student_id": [1, 2],
    "name": ["Ava", "Kate"],
    "age": [6, 15],
    "grade": [73.0, 87.0]
})

In [3]:
students

   student_id  name  age  grade
0           1   Ava    6   73.0
1           2  Kate   15   87.0

---

In [4]:
def changeDatatype(students: pd.DataFrame) -> pd.DataFrame:
    students['grade'] = students['grade'].astype(int)
    return students

In [5]:
changeDatatype(students)

   student_id  name  age  grade
0           1   Ava    6     73
1           2  Kate   15     87