In [1]:
import pandas as pd

In [2]:
animals = pd.DataFrame({
    "name": ["Tatiana", "Khaled", "Alex", "Jonathan", "Stefan", "Tommy"],
    "species": ["Snake", "Giraffe", "Leopard", "Monkey", "Bear", "Panda"],
    "age": [98, 50, 6, 45, 100, 26],
    "weight": [464, 41, 328, 463, 50, 349]
})

In [3]:
animals

       name  species  age  weight
0   Tatiana    Snake   98     464
1    Khaled  Giraffe   50      41
2      Alex  Leopard    6     328
3  Jonathan   Monkey   45     463
4    Stefan     Bear  100      50
5     Tommy    Panda   26     349

---

In [4]:
def findHeavyAnimals(animals):
    return animals[animals['weight'] > 100].sort_values(by='weight', ascending=False)[['name']]

In [5]:
findHeavyAnimals(animals)

       name
0   Tatiana
3  Jonathan
5     Tommy
2      Alex